### ISSUE TITLE
ability to set displayPriority on Annotations

### ISSUE THREAD

**Issue by andrey-abstracted** [Nicolapps/mapkit-react#27]
You've done an incredible work here, thanks for making the component available to everyone! 

I was wondering if the displayPriority property could be added to Annotations?

**Comment by andrey-abstracted** [comment]
Disregard - I need something like zIndex and displayPriority is not that

**Comment by Nicolapps** [comment]
Thanks for the suggestion! It looks like the annotations are ordered by MapKit JS in the way they are added to the map. It is true that it’s difficult in some cases to set this precisely using mapkit-react (for instance if you want to place a new annotation between two that were already displayed beforehand).

**Comment by andrey-abstracted** [comment]
Thanks! Yes, I've noticed that. Additionally adding more annotations on the map seems to be a lot slower than just adding an initial set of annotations. It is especially noticeable on mobile. Is there anything I could potentially do to get around that?
