### ISSUE TITLE
https://nicolapps.github.io/mapkit-react/ doesn't work

### ISSUE THREAD

**Issue by MoOx** [Nicolapps/mapkit-react#54]
When trying to view the storybook docs, the website doesn't load.
Tried on Safari and Chrome macOS.

```
Importing a module script failed.
```

<img width="1034" alt="image" src="https://github.com/Nicolapps/mapkit-react/assets/157534/53d3e9d2-1751-442b-8b25-8b02f98a2f34">

**Comment by Nicolapps** [comment]
Hello,

Thank you for reporting this issue, I fixed it. It was caused by Storybook generating JavaScript files with underscore characters in their name, which are ignored by default by GitHub Pages.
