### ISSUE TITLE
Mouse events broken?

### ISSUE THREAD

**Issue by nidegen** [Nicolapps/mapkit-react#66]
I tried using the map mouse callbacks. `onClick` works, but it is also triggered when dragging. Is there a way to catch it? I tried listening to `onMouseUp/Down`, but they both never get called unfortunately.

Am I missing something?
```
          <Map
            token={token}
            onMouseDown={handleMouseDown}
            onMouseUp={handleMouseUp}
            onClick={handleClick}
          >
            <Marker latitude={46.52} longitude={6.57} />
          </Map>

```

**Comment by Nicolapps** [comment]
Hi @nidegen,

Sorry, I didn’t see earlier you filed an issue in this repo. The events you can attach to `<Map />` are the one exposed by MapKit JS, so I don’t have more control over them. What are you trying to achieve?

**Comment by nidegen** [comment]
Basically, I am trying to select a location on click while allowing navigation like zooming and dragging. Currently, the onClick callback always triggers when dragging too and I haven't found a way to differentiate between the events.

**Comment by Nicolapps** [comment]
@nidegen You should be able to achieve this by using the `onSingleTap` event. Have you tried it?

**Comment by nidegen** [comment]
Yep that's it 🙃

**Comment by Nicolapps** [comment]
Great!
