### ISSUE TITLE
Storybook not working locally

### ISSUE THREAD

**Issue by nikischin** [Nicolapps/mapkit-react#68]
I wanted to continue working on the clustering finally again, however, I don't get the storybook running locally anymore. I tried both `npm i;npm run storybook` and `yarn;yarn storybook`, however, in both cases I just get an empty storybook:

<img width="861" alt="image" src="https://github.com/user-attachments/assets/1543d1f6-7a14-4339-ac1a-218866cbe9ff">

I am not too familiar with storybook, and seems like there is a new version available which we might consider migrating to, but wanted to ask if it is only an issue in my local environment or some general issue. This is still the current version with both `package-lock.json` and `package.json` as is. @Nicolapps

**Comment by Nicolapps** [comment]
Hi @nikischin, thanks for reporting the issue! I was not able to reproduce it on my end. I’ve upgraded Storybook to the latest version, could you please check if this fixes the bug for you?

**Comment by nikischin** [comment]
Ah great @Nicolapps, thank you so much for the fast update! I just checked and it did the thing for me!

I am just getting some console warnings like this but don't know if they have any impact:
```
/mapkit-react/src/stories/Marker.stories.tsx
450|    window.$RefreshReg$ = prevRefreshReg;
451|    window.$RefreshSig$ = prevRefreshSig;
452|    import(import.meta.url).then((currentExports) => {
   |           ^
453|      RefreshRuntime.registerExportsForReactRefresh("/Users/tim/Dropbox (Privat)/Shootkit/Code/REACT/mapkit-react/src/stories/Marker.stories.tsx", currentExports);
454|      import.meta.hot.accept((nextExports) => {
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.
```

Also there are quite some other outdated dev dependencies, and I was wondering if we should update some of those maybe?

<img width="433" alt="image" src="https://github.com/user-attachments/assets/d8d11c89-5445-466b-8540-6afa351be4f4">

**Comment by Nicolapps** [comment]
Thanks for reporting! I’ve opened a ticket for the Storybook warning (#69). I’m also experiencing it myself but I’m not sure what is causing it.

I don’t have the time right now to address the dependencies issues (some of the changes, for instance eslint, require manual changes), but I’d welcome any PRs for them.

**Comment by nikischin** [comment]
> Thanks for reporting! I’ve opened a ticket for the Storybook warning (#69). I’m also experiencing it myself but I’m not sure what is causing it.
> 
> I don’t have the time right now to address the dependencies issues (some of the changes, for instance eslint, require manual changes), but I’d welcome any PRs for them.

Yeah sure no worries! Thank you so much for the quick help! 

And yes this is relatable. I finally updated ESLint in my main project just recently (after the React team finally updated their plugin). It was a real pain for me and took me a full afternoon until I figured all out, but finally got it working at some point and it finally runs stable on the new version.
